apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq-broker.fullname" . }}
  labels:
    {{- include "rocketmq-broker.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.broker.service.port }}
      targetPort: broker-port
      protocol: TCP
      name: broker-port
    - port: 22
      targetPort: 22
      protocol: TCP
      name: broker-ssh
  selector:
    {{- include "rocketmq-broker.selectorLabels" . | nindent 4 }}
  clusterIP: None
